<?php

namespace Dml\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AhorrrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AhorrosRepository extends EntityRepository {
    
    /**
     * returns el numero de imagen de acuerdo al album
     * @return int
     */
    public function ahTable() {
        return $this->createQueryBuilder('ah')
                    ->where('ah.ahBorradoLogico = :bool')
                    ->setParameter('bool', 0);
    }
    
}