<?php

namespace Dml\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContratoIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratoIpRepository extends EntityRepository
{
}
