<?php

namespace Dml\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientosRepository extends EntityRepository {
    
    /**
     * Retorna todos los datos de la tabla Movimientos
     * @return int
     */
    public function moTable() {
        return $this->createQueryBuilder('mo')
                    ->where('mo.moBorradoLogico = :bool')
                    ->setParameter('bool', 0);
    }
    
}