<?php

namespace Dml\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientosRepository extends EntityRepository {
    
    /**
     * returns el numero de imagen de acuerdo al album
     * @return int
     */
    public function allRows() {
        return $this->createQueryBuilder('mo');
    }
    
}