<?php

namespace Dml\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PagosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagosRepository extends EntityRepository {

    /**
     * Retorna todos los datos de la tabla Movimientos
     * @return int
     */
    public function paTable() {
        return $this->createQueryBuilder('pa')
                    ->where('pa.paBorradoLogico = :bool')
                    ->setParameter('bool', 0);
    }

}
