<?php

namespace Dml\TodoBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * EntidadSbbipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadSbbipRepository extends EntityRepository
{
}
