parameters:
    database_driver: pdo_mysql
    database_host: 192.168.1.13
    database_port: '3306'
    database_name: dml
    database_user: root
    database_password: '39801981'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 0253c7cf1d8c9f805ea233f85684568d0d4a79be
    database_path: null
