<?php

namespace Dml\TodoBundle\Repositories\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HijosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HijosRepository extends EntityRepository
{
}
