todo_homepage:
    pattern:  /index
    defaults: { _controller: TodoBundle:Movimientos:index }

todo_combo_cuentas:
    pattern:  /cuentas-ahorros
    defaults: { _controller: TodoBundle:Movimientos:cuentasAhorros }

todo_pagos:
    pattern: /pagos
    defaults: { _controller: TodoBundle:Pagos:index }

todo_mo_list:
    pattern: /mov-list-{page}
    defaults: { _controller: TodoBundle:Movimientos:moList, page: 1 }

todo_mo_pager:
    pattern: /mov-pager-{page}
    defaults: { _controller: TodoBundle:Movimientos:moPager, page: 1 }

todo_mo_paste:
    pattern: /pegar
    defaults: { _controller: TodoBundle:Movimientos:paste }