todo_homepage:
    pattern:  /index/{id}
    defaults: { _controller: TodoBundle:Movimientos:index }

todo_combo_cuentas:
    pattern:  /cuentas-ahorros
    defaults: { _controller: TodoBundle:Movimientos:cuentasAhorros }
