parameters:
#    todo.example.class: Dml\TodoBundle\Example

services:
#    todo.example:
#        class: %todo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    todo.twig.dml_extension:
        class   : Dml\TodoBundle\Twig\DmlExtension
        tags    :
                    - { name: twig.extension }

    todo.twig.dml_extension_functions:
        class   : Dml\TodoBundle\Twig\DmlExtensionFunctions
        tags    :
                    - { name: twig.extension }

    todo.twig.dml_extension_queries:
        class   : Dml\TodoBundle\Twig\DmlExtensionQueries
        tags    :
                    - { name: twig.extension }
        arguments:
            em  : "@doctrine.orm.entity_manager"
            
    todo.login_listener:
        class   : Dml\TodoBundle\Listener\LoginListener
        arguments: [@router, @doctrine.orm.entity_manager]
        tags    :
                    - { name: kernel.event_listener, event: security.interactive_login }
                    - { name: kernel.event_listener, event: kernel.response }

    todo.logout_listener:
        class   : Dml\TodoBundle\Listener\LogoutListener
        arguments: [@security.context, @doctrine.orm.entity_manager]