parameters:
#    todo.example.class: Dml\TodoBundle\Example

services:
#    todo.example:
#        class: %todo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    todo.twig.dml_extension:
        class   : Dml\TodoBundle\Twig\DmlExtension
        tags    :
                    - { name: twig.extension }
    todo.twig.dml_extension_queries:
        class   : Dml\TodoBundle\Twig\DmlExtensionQueries
        tags    :
                    - { name: twig.extension }
        arguments:
            em  : "@doctrine.orm.entity_manager"