Dml\TodoBundle\Entity\ContratoIp:
    type: entity
    table: CONTRATO_IP
    repositoryClass: Dml\TodoBundle\Entity\Repositories\ContratoIpRepository
    indexes:
        fk_contrato_ip_persona1_idx:
            columns:
                - persona_pe_id
        fk_contrato_ip_remuneracion1_idx:
            columns:
                - remuneracion_re_id
        fk_contrato_ip_entidades1_idx:
            columns:
                - entidades_es_id
    id:
        cipId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: cip_id
            generator:
                strategy: IDENTITY
    fields:
        cipFechaIngreso:
            type: date
            nullable: true
            comment: ''
            column: cip_fecha_ingreso
        cipFechaSalida:
            type: date
            nullable: true
            comment: ''
            column: cip_fecha_salida
        cipMotivosSalida:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: cip_motivos_salida
        cipActividadDesarrollada:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: cip_actividad_desarrollada
        cipActivo:
            type: boolean
            nullable: true
            comment: ''
            column: cip_activo
    manyToOne:
        personaPe:
            targetEntity: Persona
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                persona_pe_id:
                    referencedColumnName: pe_id
            orphanRemoval: false
        remuneracionRe:
            targetEntity: Remuneracion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                remuneracion_re_id:
                    referencedColumnName: re_id
            orphanRemoval: false
        entidadesEs:
            targetEntity: Entidades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                entidades_es_id:
                    referencedColumnName: es_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
