Dml\TodoBundle\Entity\TipoConsumo:
    type: entity
    table: TIPO_CONSUMO
    repositoryClass: Dml\TodoBundle\Entity\TipoConsumoRepository
    id:
        tcId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: tc_id
            generator:
                strategy: IDENTITY
    fields:
        tcNombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: tc_nombre
        tcAlias:
            type: string
            nullable: true
            length: 2
            fixed: true
            comment: ''
            column: tc_alias
        tcFechaCrea:
            type: datetime
            nullable: true
            comment: ''
            column: tc_fecha_crea
        tcQuienCrea:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: tc_quien_crea
        tcFechaModifica:
            type: datetime
            nullable: true
            comment: ''
            column: tc_fecha_modifica
        tcQuienModifica:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: tc_quien_modifica
        tcBorradoLogico:
            type: boolean
            nullable: true
            comment: ''
            column: tc_borrado_logico
    lifecycleCallbacks: {  }
